send error output to stderr

diff --git a/tools/fftw-wisdom-to-conf.in b/tools/fftw-wisdom-to-conf.in
--- a/tools/fftw-wisdom-to-conf.in
+++ b/tools/fftw-wisdom-to-conf.in
@@ -7,7 +7,7 @@ case "$preamble $fftw_wisdom" in
 		prefix=`echo $fftw_wisdom | cut -d_ -f1`_
 		;;
 	*)
-		echo "fftw-wisdom2c: invalid wisdom"
+		echo "fftw-wisdom2c: invalid wisdom" 1>&2
 		exit 1
 		;;
 esac
