Removed obsolete name fftw-wisdom2c.

diff --git a/tools/fftw-wisdom-to-conf.in b/tools/fftw-wisdom-to-conf.in
--- a/tools/fftw-wisdom-to-conf.in
+++ b/tools/fftw-wisdom-to-conf.in
@@ -43,7 +43,7 @@ case "$preamble $fftw_wisdom" in
 		prefix=`echo $fftw_wisdom | cut -d_ -f1`_
 		;;
 	*)
-		echo "fftw-wisdom2c: invalid wisdom" 1>&2
+		echo "fftw-wisdom-to-conf: invalid wisdom" 1>&2
 		exit 1
 		;;
 esac
